<?php

Class Mimes {

  public static $List = Array(
    'hqx'	=>	Array('application/mac-binhex40', 'application/mac-binhex', 'application/x-binhex40', 'application/x-mac-binhex40'),
    'cpt'	=>	'application/mac-compactpro',
    'csv'	=>	Array('text/x-comma-separated-values', 'text/comma-separated-values', 'application/octet-stream', 'application/vnd.ms-excel', 'application/x-csv', 'text/x-csv', 'text/csv', 'application/csv', 'application/excel', 'application/vnd.msexcel', 'text/plain'),
    'bin'	=>	Array('application/macbinary', 'application/mac-binary', 'application/octet-stream', 'application/x-binary', 'application/x-macbinary'),
    'dms'	=>	'application/octet-stream',
    'lha'	=>	'application/octet-stream',
    'lzh'	=>	'application/octet-stream',
    'exe'	=>	Array('application/octet-stream', 'application/x-msdownload'),
    'class'	=>	'application/octet-stream',
    'psd'	=>	Array('application/x-photoshop', 'image/vnd.adobe.photoshop'),
    'so'	=>	'application/octet-stream',
    'sea'	=>	'application/octet-stream',
    'dll'	=>	'application/octet-stream',
    'oda'	=>	'application/oda',
    'pdf'	=>	Array('application/pdf', 'application/force-download', 'application/x-download', 'binary/octet-stream'),
    'ai'	=>	Array('application/pdf', 'application/postscript'),
    'eps'	=>	'application/postscript',
    'ps'	=>	'application/postscript',
    'smi'	=>	'application/smil',
    'smil'	=>	'application/smil',
    'mif'	=>	'application/vnd.mif',
    'xls'	=>	Array('application/vnd.ms-excel', 'application/msexcel', 'application/x-msexcel', 'application/x-ms-excel', 'application/x-excel', 'application/x-dos_ms_excel', 'application/xls', 'application/x-xls', 'application/excel', 'application/download', 'application/vnd.ms-office', 'application/msword'),
    'ppt'	=>	Array('application/powerpoint', 'application/vnd.ms-powerpoint', 'application/vnd.ms-office', 'application/msword'),
    'pptx'	=> 	Array('application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/x-zip', 'application/zip'),
    'wbxml'	=>	'application/wbxml',
    'wmlc'	=>	'application/wmlc',
    'dcr'	=>	'application/x-director',
    'dir'	=>	'application/x-director',
    'dxr'	=>	'application/x-director',
    'dvi'	=>	'application/x-dvi',
    'gtar'	=>	'application/x-gtar',
    'gz'	=>	'application/x-gzip',
    'gzip'  =>	'application/x-gzip',
    'php'	=>	Array('application/x-httpd-php', 'application/php', 'application/x-php', 'text/php', 'text/x-php', 'application/x-httpd-php-source'),
    'php4'	=>	'application/x-httpd-php',
    'php3'	=>	'application/x-httpd-php',
    'phtml'	=>	'application/x-httpd-php',
    'phps'	=>	'application/x-httpd-php-source',
    'js'	=>	Array('application/x-javascript', 'text/plain'),
    'swf'	=>	'application/x-shockwave-flash',
    'sit'	=>	'application/x-stuffit',
    'tar'	=>	'application/x-tar',
    'tgz'	=>	Array('application/x-tar', 'application/x-gzip-compressed'),
    'z'	=>	'application/x-compress',
    'xhtml'	=>	'application/xhtml+xml',
    'xht'	=>	'application/xhtml+xml',
    'zip'	=>	Array('application/x-zip', 'application/zip', 'application/x-zip-compressed', 'application/s-compressed', 'multipart/x-zip'),
    'rar'	=>	Array('application/x-rar', 'application/rar', 'application/x-rar-compressed'),
    'mid'	=>	'audio/midi',
    'midi'	=>	'audio/midi',
    'mpga'	=>	'audio/mpeg',
    'mp2'	=>	'audio/mpeg',
    'mp3'	=>	Array('audio/mpeg', 'audio/mpg', 'audio/mpeg3', 'audio/mp3'),
    'aif'	=>	Array('audio/x-aiff', 'audio/aiff'),
    'aiff'	=>	Array('audio/x-aiff', 'audio/aiff'),
    'aifc'	=>	'audio/x-aiff',
    'ram'	=>	'audio/x-pn-realaudio',
    'rm'	=>	'audio/x-pn-realaudio',
    'rpm'	=>	'audio/x-pn-realaudio-plugin',
    'ra'	=>	'audio/x-realaudio',
    'rv'	=>	'video/vnd.rn-realvideo',
    'wav'	=>	Array('audio/x-wav', 'audio/wave', 'audio/wav'),
    'bmp'	=>	Array('image/bmp', 'image/x-bmp', 'image/x-bitmap', 'image/x-xbitmap', 'image/x-win-bitmap', 'image/x-windows-bmp', 'image/ms-bmp', 'image/x-ms-bmp', 'application/bmp', 'application/x-bmp', 'application/x-win-bitmap'),
    'gif'	=>	'image/gif',
    'jpeg'	=>	Array('image/jpeg', 'image/pjpeg'),
    'jpg'	=>	Array('image/jpeg', 'image/pjpeg'),
    'jpe'	=>	Array('image/jpeg', 'image/pjpeg'),
    'jp2'	=>	Array('image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'),
    'j2k'	=>	Array('image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'),
    'jpf'	=>	Array('image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'),
    'jpg2'	=>	Array('image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'),
    'jpx'	=>	Array('image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'),
    'jpm'	=>	Array('image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'),
    'mj2'	=>	Array('image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'),
    'mjp2'	=>	Array('image/jp2', 'video/mj2', 'image/jpx', 'image/jpm'),
    'png'	=>	Array('image/png',  'image/x-png'),
    'tiff'	=>	'image/tiff',
    'tif'	=>	'image/tiff',
    'css'	=>	Array('text/css', 'text/plain'),
    'html'	=>	Array('text/html', 'text/plain'),
    'htm'	=>	Array('text/html', 'text/plain'),
    'shtml'	=>	Array('text/html', 'text/plain'),
    'txt'	=>	'text/plain',
    'text'	=>	'text/plain',
    'log'	=>	Array('text/plain', 'text/x-log'),
    'rtx'	=>	'text/richtext',
    'rtf'	=>	'text/rtf',
    'xml'	=>	Array('application/xml', 'text/xml', 'text/plain'),
    'xsl'	=>	Array('application/xml', 'text/xsl', 'text/xml'),
    'mpeg'	=>	'video/mpeg',
    'mpg'	=>	'video/mpeg',
    'mpe'	=>	'video/mpeg',
    'qt'	=>	'video/quicktime',
    'mov'	=>	'video/quicktime',
    'avi'	=>	Array('video/x-msvideo', 'video/msvideo', 'video/avi', 'application/x-troff-msvideo'),
    'movie'	=>	'video/x-sgi-movie',
    'doc'	=>	Array('application/msword', 'application/vnd.ms-office'),
    'docx'	=>	Array('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/zip', 'application/msword', 'application/x-zip'),
    'dot'	=>	Array('application/msword', 'application/vnd.ms-office'),
    'dotx'	=>	Array('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/zip', 'application/msword'),
    'xlsx'	=>	Array('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/zip', 'application/vnd.ms-excel', 'application/msword', 'application/x-zip'),
    'word'	=>	Array('application/msword', 'application/octet-stream'),
    'xl'	=>	'application/excel',
    'eml'	=>	'message/rfc822',
    'json'  =>	Array('application/json', 'text/json'),
    'pem'   =>	Array('application/x-x509-user-cert', 'application/x-pem-file', 'application/octet-stream'),
    'p10'   =>	Array('application/x-pkcs10', 'application/pkcs10'),
    'p12'   =>	'application/x-pkcs12',
    'p7a'   =>	'application/x-pkcs7-signature',
    'p7c'   =>	Array('application/pkcs7-mime', 'application/x-pkcs7-mime'),
    'p7m'   =>	Array('application/pkcs7-mime', 'application/x-pkcs7-mime'),
    'p7r'   =>	'application/x-pkcs7-certreqresp',
    'p7s'   =>	'application/pkcs7-signature',
    'crt'   =>	Array('application/x-x509-ca-cert', 'application/x-x509-user-cert', 'application/pkix-cert'),
    'crl'   =>	Array('application/pkix-crl', 'application/pkcs-crl'),
    'der'   =>	'application/x-x509-ca-cert',
    'kdb'   =>	'application/octet-stream',
    'pgp'   =>	'application/pgp',
    'gpg'   =>	'application/gpg-keys',
    'sst'   =>	'application/octet-stream',
    'csr'   =>	'application/octet-stream',
    'rsa'   =>	'application/x-pkcs7',
    'cer'   =>	Array('application/pkix-cert', 'application/x-x509-ca-cert'),
    '3g2'   =>	'video/3gpp2',
    '3gp'   =>	Array('video/3gp', 'video/3gpp'),
    'mp4'   =>	'video/mp4',
    'm4a'   =>	'audio/x-m4a',
    'f4v'   =>	Array('video/mp4', 'video/x-f4v'),
    'flv'	=>	'video/x-flv',
    'webm'	=>	'video/webm',
    'aac'   =>	'audio/x-acc',
    'm4u'   =>	'application/vnd.mpegurl',
    'm3u'   =>	'text/plain',
    'xspf'  =>	'application/xspf+xml',
    'vlc'   =>	'application/videolan',
    'wmv'   =>	Array('video/x-ms-wmv', 'video/x-ms-asf'),
    'au'    =>	'audio/x-au',
    'ac3'   =>	'audio/ac3',
    'flac'  =>	'audio/x-flac',
    'ogg'   =>	Array('audio/ogg', 'video/ogg', 'application/ogg'),
    'kmz'	=>	Array('application/vnd.google-earth.kmz', 'application/zip', 'application/x-zip'),
    'kml'	=>	Array('application/vnd.google-earth.kml+xml', 'application/xml', 'text/xml'),
    'ics'	=>	'text/calendar',
    'ical'	=>	'text/calendar',
    'zsh'	=>	'text/x-scriptzsh',
    '7z'	=>	Array('application/x-7z-compressed', 'application/x-compressed', 'application/x-zip-compressed', 'application/zip', 'multipart/x-zip'),
    '7zip'	=>	Array('application/x-7z-compressed', 'application/x-compressed', 'application/x-zip-compressed', 'application/zip', 'multipart/x-zip'),
    'cdr'	=>	Array('application/cdr', 'application/coreldraw', 'application/x-cdr', 'application/x-coreldraw', 'image/cdr', 'image/x-cdr', 'zz-application/zz-winassoc-cdr'),
    'wma'	=>	Array('audio/x-ms-wma', 'video/x-ms-asf'),
    'jar'	=>	Array('application/java-archive', 'application/x-java-application', 'application/x-jar', 'application/x-compressed'),
    'svg'	=>	Array('image/svg+xml', 'application/xml', 'text/xml'),
    'vcf'	=>	'text/x-vcard',
    'srt'	=>	Array('text/srt', 'text/plain'),
    'vtt'	=>	Array('text/vtt', 'text/plain'),
    'ico'	=>	Array('image/x-icon', 'image/x-ico', 'image/vnd.microsoft.icon'),
    'odc'	=>	'application/vnd.oasis.opendocument.chart',
    'otc'	=>	'application/vnd.oasis.opendocument.chart-template',
    'odf'	=>	'application/vnd.oasis.opendocument.formula',
    'otf'	=>	'application/vnd.oasis.opendocument.formula-template',
    'odg'	=>	'application/vnd.oasis.opendocument.graphics',
    'otg'	=>	'application/vnd.oasis.opendocument.graphics-template',
    'odi'	=>	'application/vnd.oasis.opendocument.image',
    'oti'	=>	'application/vnd.oasis.opendocument.image-template',
    'odp'	=>	'application/vnd.oasis.opendocument.presentation',
    'otp'	=>	'application/vnd.oasis.opendocument.presentation-template',
    'ods'	=>	'application/vnd.oasis.opendocument.spreadsheet',
    'ots'	=>	'application/vnd.oasis.opendocument.spreadsheet-template',
    'odt'	=>	'application/vnd.oasis.opendocument.text',
    'odm'	=>	'application/vnd.oasis.opendocument.text-master',
    'ott'	=>	'application/vnd.oasis.opendocument.text-template',
    'oth'	=>	'application/vnd.oasis.opendocument.text-web'
  );
  
  public static function get($ext = '',$index = -1){
    if( $ext == '' ){
      return self::$List;
    }
    else{
      if( isset( self::$List[$ext] ) ){
        if( $index != -1 ){
          if( count(self::$List[$ext]) > $index ) return self::$List[$ext][$index];
          else return self::$List[$ext][0];
        }
        else return self::$List[$ext];
      }
      else return NULL;
    }
  }

}

?>